### ISSUE TITLE
repeated channel name

### ISSUE THREAD

**Issue by dieloz** [robertoostenveld/bids#10]
https://github.com/robertoostenveld/bids-tools/blob/5acdd3a942b299c9e3347bb8a3ee171824421d2e/lib/pybids/channels.py#L18

Hi Robert,
the /lib/pybids/channels.py lines 18-19 has different channel number but equal name (HEOG). This creates the following errror when I try to convert the workshop dataset to BIDS:

dlozano@IBP10091:~$ $BIDSTOOLS/create_sidecar_files  -f --description  $BIDSROOT   # create the dataset_description.json file
Traceback (most recent call last):
  File "/media/dlozano/Data/matlab/bids-tools/bin/create_sidecar_files", line 46, in <module>
    from pybids import channels
  File "/media/dlozano/Data/matlab/bids-tools/bin/../lib/pybids/channels.py", line 8, in <module>
    class type(Enum):
  File "/media/dlozano/Data/matlab/bids-tools/bin/../lib/pybids/channels.py", line 19, in type
    HEOG        = 12   #  Horizontal ElectroOculoGram (eyes)
  File "/home/dlozano/anaconda3/lib/python3.6/enum.py", line 92, in __setitem__
    raise TypeError('Attempted to reuse key: %r' % key)
TypeError: Attempted to reuse key: 'HEOG'

Shall I delete one of them?

**Comment by dieloz** [comment]
So far, the bash finishes commenting L11. I'll check later what's going on
